version = 1

[[annotations]]
path = [ "CNAME", "metadata/**" ]
SPDX-FileCopyrightText = "Copyright 2025 Léo de Souza"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "favicon.ico", "src/main/res/mipmap-*dpi/ic_launcher.webp" ]
SPDX-FileComment = "Adapted from the av_timer glyph in the Material Icons Round font"
SPDX-FileCopyrightText = """
Copyright 2025 Léo de Souza
Copyright 2019 Google, Inc."""
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle**"
SPDX-FileCopyrightText = "Copyright 2025 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"
